### ISSUE TITLE
how to improve seo by chromedp?

### ISSUE THREAD

**Issue by meilihao** [chromedp/examples#13]
we need an example what is able to reduce the intial DOM load latency by skip fetching and rendering unnecessary content CSS, fonts, images, etc...

**Comment by jtarchie** [comment]
Why not a standard HTTP request, rather than the browser then? It seems you don't need the browser functionality if no CSS, fonts, images are required.

**Comment by mvdan** [comment]
Once we've adapted this repository to the new chromedp API, if anyone wants to contribute more examples, PRs are welcome.
