### ISSUE TITLE
Timeout waiting for initial target when running in standalone

### ISSUE THREAD

**Issue by olicuzo** [chromedp/examples#15]
Hi,
I'm getting `timeout waiting for initial target` even when running some of the examples and in particular the `examples/standalone` one. I'm following the exact steps from the README - running the latest headless shell, compiling and running the code - I still get the same error. 

```
go version go1.12 darwin/amd64
"Image": "sha256:7e34e194ab48938fd5595c7e14d43a491d4ce0835d4f803eb2dec057b991de13
```

What's weirder is that I get the same error when trying to run some code (again standalone) in kubernetes, so it's either a configuration issue or a bug.

**Comment by kenshaw** [comment]
Please note we're in the middle of rewriting all of the examples to work with the new API. Some of the previous timeout issues are addressed using the new version of chromedp. That said, I can speak from experience that when running through virtualization like Kubernetes, it's not really practical to use chromedp without significant tweaks to the timeouts, as a VM/container typically responds much slower than working even with comparable non-virtualized hardware.

**Comment by olicuzo** [comment]
Thanks for the response. 
Chromedp and headless shell run as sidecar containers, but I would definitely try tweaking the timeouts. Are there any configurations which enable that?
