### ISSUE TITLE
screenshot example takes weirdly-cropped screenshots

### ISSUE THREAD

**Issue by adiabatic** [chromedp/examples#17]
I'm new to chromedp, so forgive me if I'm stumbling over Chrome weirdnesses…

I downloaded and ran the screenshot example and it got me this screenshot (it's supposed to be of `#main` on <https://www.google.com>:

![google-home-page](https://user-images.githubusercontent.com/101246/56977744-c0442280-6b2a-11e9-8375-5c53e7532075.png)

I was not expecting the screenshot to be cropped like this. I would've thought that the screenshot would contain everything that's tinted when I hover my mouse pointer over that particular div in Chrome's DOM inspector.

When I change the `screenshot` call to ` screenshot("https://www.fishshell.com/", "#platform_tabs", &buf))`, the screenshot generated there isn't quite what I expect, either:

![fish-shell-tabs](https://user-images.githubusercontent.com/101246/56978297-08177980-6b2c-11e9-8853-f01f96f04407.png)

The `ul` isn't that tall (it doesn't go under the "Homebrew" and "MacPorts" buttons below it) and it extends all the way to the right edge of the page.

Any idea what's going on?

**Comment by mvdan** [comment]
Please use chromedp's main issue tracker.

The problem here is likely that you're not setting a window size large enough.
