### ISSUE TITLE
using standalone example with another port

### ISSUE THREAD

**Issue by AmrAlfoly** [chromedp/examples#3]
i am trying to use the standalone example but with another port number away from 9222
is it possible ?
this is the current code :
[https://github.com/chromedp/examples/blob/master/standalone/main.go](url)

**Comment by kenshaw** [comment]
Yes -- create a `runner.Runner` by calling `runner.New()` or `runner.Run` with the `runner.Port` option, and then call `chromedp.New` with the `chromedp.WithTargets` option, passing targets from the runner:

```go
      ctxt := context.Background()
      r, err := runner.Run(ctxt, runner.Port(9000))
      if err != nil {
          log.Fatal(err)
      }
      c, err := chromedp.New(ctxt, chromedp.WithTargets(r.WatchPageTargets(ctxt)))
      if err != nil {
          log.Fatal(err)
      }
```
