### ISSUE TITLE
Where is this syntax documented?

### ISSUE THREAD

**Issue by swizzley** [chromedp/examples#4]
https://github.com/chromedp/examples/blob/master/logic/main.go#L67
`sel := fmt.Sprintf(`//p[text()[contains(., '%s')]]`, sect)`

I've looked around to understand this search syntax but am coming up empty on how to write this query. 

Is this example one of these???  

https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-searchInResponseBody
https://chromedevtools.github.io/devtools-protocol/tot/Debugger/#method-searchInContent

Could someone please point me to documentation on how to use this selector?

**Comment by kenshaw** [comment]
This is XPath. `chromedp` sends the query selectors to the various Chrome Debugging Protocol API calls, based on the associated query selector used. In the `chromedp` actions, generally the default query selector used is `BySearch`. This wraps the Chrome Debugging Protocol API call `DOM.PerformSearch`. That API supports both CSS and XPath selector syntax, and will, more-or-less, return the same results as when you bring up the "search box" in Chrome DevTools.

There are a couple other `By*` query selectors in `chromedp` that wrap different API calls or convenience wrappers around the different ways that the Chrome Debugging Protocol requires fetching/retrieving node information from the Chrome protocol.

Please see the GoDoc API listing: https://godoc.org/github.com/chromedp/chromedp#BySearch

(the above links to `BySearch`, but all of the query selectors are named `By*`)

**Comment by kenshaw** [comment]
Let me summarize what the Chrome Debugging Protocol APIs are for:

|`chromedp` Selector|Chrome Debugging Protocol Equiv|Description|
|---|---|---|
|`BySearch`|`DOM.performSearch`|Executes a XPath or CSS search query, based on the provided syntax. Default query selector in `chromedp`. Similar to doing a search (ie, hitting `Ctrl-F` in Chrome DevTools)|
|`ByID`|`DOM.performSearch`|Forces a CSS query for the specified ID|
|`ByNodeID`|`DOM.RequestChildNodes`|Retrieves a specific node (must know in advance the assigned node ID)|
|`ByQuery`|`DOM.QuerySelector`|Executes a CSS query on a specific node, returning only one child node| 
|`ByQueryAll`|`DOM.QuerySelectorAll`|Executes a CSS query on a specific node, returning all matching child nodes|

**Comment by swizzley** [comment]
Thank you very much, you answered my question. XPATH or CSS search queries have syntax easily looked up and that is the missing piece for me. eg: https://www.w3schools.com/xml/xpath_syntax.asp
