### ISSUE TITLE
Question: Is possible to work with chromedp without opening the actual Chrome browser

### ISSUE THREAD

**Issue by alejoloaiza** [chromedp/examples#8]
Hi, is there any way to work with this tool but not opening the browser in the machine, something like a headless chrome kind of thing but using chromedp.

Thanks a lot.

Regards.

**Comment by kenshaw** [comment]
Yes, this was designed around `headless_shell` mainly. Please use the `runner.HeadlessPathPort` option:
```go
import (
    "github.com/chromedp/chromedp/runner"
    "github.com/chromedp/chromedp"
)

c, err := chromedp.New(chromedp.WithRunnerOptions(
    runner.HeadlessPathPort("/path/to/headless_chrome", 9222),
))
```

Alternately, you can launch your own Chrome, and either create your own `client.Client` or `runner.Runner` and use that with `chromedp.New()`:

```go
import (
    "github.com/chromedp/chromedp/runner"
    "github.com/chromedp/chromedp/client"
    "github.com/chromedp/chromedp"
)

c1, err := chromedp.New(chromedp.WatchTargets(
    client.New(/* ... client options ... */).WatchPageTargets(context.Background()),
))

r, err := runner.New(runner.Flag("headless", "true"), runner.Flag("remote-debugging-port", 9222))
c2, err := chromedp.New(chromedp.WithRunner(r))
```

Please see the `runner` and `client` packages for all the various options that can be passed. It's worth noting you don't even need to use the `client` or `runner` packages, as all `chromedp` needs are the `targets` which is simply a channel that sends `client.Target` (which is an interface type).

Any command line flag can be issued to the `runner.New`, and the most commonly used ones have defined versions. Please see the [GoDoc](https://godoc.org/github.com/chromedp/chromedp) page.
